name: Test Audio Tools

on: [workflow_dispatch]

jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check ffmpeg
        run: ffmpeg -version
      - name: Check yt-dlp
        run: |
          python3 -m pip install yt-dlp
          yt-dlp --version
      - name: Check yt-dlp supports key platforms
        run: |
          yt-dlp --list-extractors | grep -E "twitter|youtube|clubhouse|linkedin" | head -10
